possibilities={
    'Holly Dolly':['Polka Song','Kanikuly','Merci','Holly Dolly'],
    'Billie Jean':['Thriller', 'Billie Jean', 'Come On', 'Infinity'],
    'Scenariusz Dla Moich Sasiadow':['Scenariusz Dla Moich Sasiadow', 'Serce Me', 'Historia Jednej Znajomosci', 'Czerwona Sukienka'],
    'Beds Are Burning':['Friend in Deed' ,'Sour Love', 'Beds Are Burning', 'Dark Time'],
    'We Built This City':['Geronimo\'s Cadillac','War Machine','Brother Louie', 'We Built This City'],
    'Espanol':['Espanol', 'Papa\'s Got a New Pigbag', 'El Mismo Sol', 'Bailar'],
    'Hit That':['Thunderstruck','Hit That', 'Defy You', 'What Happened to You'],
    'Perry Mason Theme':['Pixelated', 'Think', 'Perry Mason Theme', 'Inspector Harry'],
    'Pixelated':['Still with You', 'Stay with Me Babe','Mama Said','Pixelated'],
    'Propaganda':['Big Baton', 'Luźny Łan', 'Burza w Porcie Winczeston','Propaganda'],
    'Roll With It':['Roll With It', 'Little by Little', 'Stand by Me','Story of me'],
    'Bird of Paradise':['Heaven','The Light','Bird of Paradise','Clouds'],
    'Blurred Lines':['Freaky Me','Hey Hey','Dance','Blurred Lines'],
    'Hope of Deliverance':['Hope of Deliverance','Right','Forever','With You'],
    'Hump De Bump':['Funky Room','Hump De Bump','Jump','Party'],
    'I need a Dollar':['Crisis','Sad Times','I need a Dollar','Dinero'],
    'La Camisa Negra':['El Toro','Mi Amor','Manzana Rosa','La Camisa Negra'],
    'One More Night':['Fighting Club','One More Night','For You','Baby'],
    'Orinoco Flow':['Orinoco Flow','Africa','Rivers of Babylon','Argentina'],
    'Rock or Bust':['Rock or Bust','Dirty Deeds','Hard Stones','Fight'],
    'Slabo Day':['Breathe','Slabo Day','The Protector Theme','Home'],
    'Tequila':['Quanto Camino','El Paso','Tequila','Mexico'],
    'The Flood':['Canoying','Hollywood','Supreme','The Flood'],
    'The Weekend':['Celebrate','Party Time','The Weekend','Take a Chance'],
    'W porownaniu':['W porownaniu','Wszyscy to wiedzą','Wielki Tenis','Radość'],
    'You Don\'t Fool Me':['Hammer to Fall','You Don\'t Fool Me','Love Kills','Another One Bites the Dust'],
    'I\'m a believer':['I\'m a believer', 'Can\'t Stop Me', 'Beverly Hills', 'Murphy'],
    'Teo And Tea':['Oxygen', 'Teo And Tea', 'Outer Space', 'Michelle'],
    'Hound dog':['No More', 'Little Less Conversation', 'Hound dog', 'Rock This House'],
    'Hiszpan':['Corrida', 'Guitar Tango', 'Byk', 'Hiszpan'],
    'Alane':['Alane','Catharsis', 'Nomhade', 'Aconcagua'],
    'All star':['Glitters', 'All star', 'Boundled Out', 'Stupid'],
    'Bitter Sweet Symphony':['Together', 'Cruel World', 'Bitter Sweet Symphony', 'You and Me'],
    'Can\'t Touch This':['Nigga', 'Stolen Pants', 'Stop me, Bro!', 'Can\'t Touch This'],
    'Down Under':['Down Under', 'Bread', 'Australia', 'Hot sand'],
    'Kawalek do tanca':['Wakacje', 'Kawalek do tanca', 'Dziewczyna - ogień', 'Gra wstępna'],
    'Lubie mowic z Toba':['Naiwne pytania', 'Nie odchodź', 'Lubie mowic z Toba', 'Jeszcze raz'],
    'Need You Tonight':['Erotic', 'Come closer', 'Hush', 'Need You Tonight'],
    'Panic Station':['Panic Station', 'Strength in Numbers', 'Drunken', 'Revolution'],
    'Planetary':['Progress','Planetary','Possibilities', 'Miss Alissa'],
    'September':['November', 'October', 'September', 'December'],
    'Skora':['Uliczne opowiastki', 'Odejdź', 'Posłuchaj', 'Skora'],
    'Sugar':['Sugar', 'Sweet Lovin', 'Ghost Town', 'Maria'],
    'Sweet Home Alabama':['Muscle Shoals','Sweet Home Alabama','Country roads', 'Night by Lake'],
    'Trojkaty i Kwadraty':['Para', 'Uciekam', 'Trojkaty i Kwadraty', 'Piosenka pisana nocą'],
    'Twoje oczy lubia mnie':['Chodź do mnie','Narkoman','Krzyk muzyka','Twoje oczy lubia mnie'],
    'Wonderwall':['Wonderwall', 'Lately', 'You Wanna Know', 'Stand with me'],
    'Wpusc mnie':['Zanim pojde', 'Wpusc mnie', 'Zostań ze mną', 'Z całych sił'],
    'Zakrecona':['Zostań z nami', 'Mody szyk', 'Zakrecona', 'Wieczór z nastolatką'],
    'Jumping Jack Flash':['On a Plain', 'Stereo Heart', 'Rock in a hard place', 'Jumping Jack Flash']
    }
